trigger:
- master
- development

jobs:
- job: Xcode_test
  strategy:
    maxParallel: 10
    matrix:
      #iOS 9+10 simulators requires macos-10.13, which is not supported by Azure Pipelines anymore...
      #iOS 11 simulators requires macos-10.14 and the Xcode version does not support Swift 5...
      ios12:
        IMAGE_NAME: 'macos-10.15'
        XCODE_DEVELOPER_PATH: /Applications/Xcode_10.3.app
        IOS_SIMULATORS: 'iPhone X,OS=12.4'
      ios13:
        IMAGE_NAME: 'macos-10.15'
        XCODE_DEVELOPER_PATH: /Applications/Xcode_11.7.app
        IOS_SIMULATORS: 'iPhone 8,OS=13.7'
      ios14:
        IMAGE_NAME: 'macos-10.15'
        XCODE_DEVELOPER_PATH: /Applications/Xcode_12.app
        IOS_SIMULATORS: 'iPhone 11,OS=14.0'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'TriforkSwiftExtensions'
      sdk: 'iphonesimulator'
      configuration: 'Debug'
      xcWorkspacePath: '**/TriforkSwiftExtensions/TriforkSwiftExtensions.xcodeproj'
      xcodeVersion: 'specifyPath'
      xcodeDeveloperDir: $(XCODE_DEVELOPER_PATH)
      signingOption: 'auto'
      useXcpretty: true
      publishJUnitResults: true
      destinationSimulators: $(IOS_SIMULATORS)
      destinationTypeOption: 'simulators'
      destinationPlatformOption: 'iOS'

- job: Danger
  pool:
    vmImage: 'macOS-10.14'
    variables:
      DEVELOPER_DIR: /Applications/Xcode_10.2.app
  steps:
    - script: bundle update --bundler
      displayName: Update bundler
    - script: bundle install
      displayName: bundle install
    - script: bundle exec danger --verbose
      displayName: Run Danger

      env:
        DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
